### ISSUE TITLE
Remove environment hardcoding

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/quantum-mechanic#101]
We have many instances of the use of hardcoded environment strings uat, sit, dev. It will be necessary to find a way to better handle the environment selection in future. Perhaps an options menu such as:

Please select the environment you wish to provision
- Dev
- SIT
- UAT
- All

This information will need to be stored against the project for future reference.

**Comment by donovanmuller** [comment]
This is tricky at the moment because of the complexity this will add to the Jenkins pipelines etc.

Need a good design around this. If we adopt something like https://the-composition.com/why-you-need-a-software-delivery-machine-85e8399cdfc0 then this could change. Not trivial at least...

**Comment by kbristow** [comment]
It is not. But our current solution is outright bad right now :)
