### ISSUE TITLE
Remove explicit proxy setting

### ISSUE THREAD

**Issue by chriskieser** [absa-subatomic/quantum-mechanic#112]
Currently setting `proxy: false` in Axios create options. This should respect the environment NO_PROXY variable instead

**Comment by kbristow** [comment]
I think this is meant to be supported in the next axios release. When you say it should respect the NO_PROXY variable are you suggesting putting some logic into QM to create an axios wrapper to set `proxy: false` based on NO_PROXY value or just in general we need to keep it in mind?

**Comment by chriskieser** [comment]
That is a reasonable work around

**Comment by chriskieser** [comment]
Check if new Axios is released

**Comment by chriskieser** [comment]
Atomist has forked Axios. Closing this issue as we have no control over it
