### ISSUE TITLE
Migrate the usage of the oc CLI tool to using the OpenShift/Kubernetes API

### ISSUE THREAD

**Issue by donovanmuller** [absa-subatomic/quantum-mechanic#13]
The `oc` CLI tool is not suited to concurrent usage and currently means that execution must be serialised to avoid race conditions and corruption of the `~/.kube/config` file.

**Comment by chriskieser** [comment]
According to https://bugzilla.redhat.com/show_bug.cgi?id=1328480, if we do not modify the config file (logging in or change context) we should be okay. Just the `oc login` that needs to be looked at in qm

**Comment by chriskieser** [comment]
Closing. Can reopen if/when we definitely require this
