### ISSUE TITLE
Provide ability for member to capture domain password

### ISSUE THREAD

**Issue by donovanmuller** [absa-subatomic/quantum-mechanic#2]
After submitting command to onboard member:

* present a URL link
* the web application at this location will ask the member to authenticate using their domain credentials (username pre-populated from command parameter)
* the member's password will be encrypted and stored in Gluon under the members profile
* and then the member is onboarded successfully

The member's password will be used to authenticate as the member when integrating with external systems like Bitbucket Server and OpenShift. I.e. integrations will be executed as the member and not as a Subatomic system account.

**Comment by donovanmuller** [comment]
Given certain future design decisions, this may no longer be required. Will have to be reviewed at a later date.

**Comment by chriskieser** [comment]
closing for now
