### ISSUE TITLE
When linking an existing Slack channel to a team via the direct command intent, use a menu to select the team to link too

### ISSUE THREAD

**Issue by donovanmuller** [absa-subatomic/quantum-mechanic#24]
As per this comment: https://github.com/absa-subatomic/quantum-mechanic/pull/22#issuecomment-364019430

When directly linking an existing Slack channel to a team via the `link team channel` intent. Instead of asking the member to type the name of the team he would like to link an existing Slack channel to, rather render a menu populated with all the teams that this member is a part of. Then the member can select the team for a better use experience.

**Comment by kbristow** [comment]
This functionality should be applied when creating a new slack team in addition to when linking to an existing slack channel.

**Comment by donovanmuller** [comment]
Shouldn't have any effect. This just covers which team to select to link the Slack channel too. On typing the name of the existing channel, this will then be handled by #44.
