### ISSUE TITLE
Adding Jenkins files can fail if master branch is protected

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/quantum-mechanic#362]
When we attempt add jenkins files to repo's that have protected master branches the command fails uninformatively. We should catch failures when trying to push to master and alert the users as to why this happened and how to fix it (I.E. either open master or create a Jenkins file manually).

**Comment by lancedfr** [comment]
> I.E. either open master or create a Jenkins file manually

or give atomist git user permission to push to master

**Comment by Buzzglo** [comment]
completed
