### ISSUE TITLE
Should show jenkins URL

### ISSUE THREAD

**Issue by andrejonathan** [absa-subatomic/quantum-mechanic#420]
After the initial setup for the team/project we should output the Jenkins URL in slack

**Comment by kbristow** [comment]
This already happens:
<img width="781" alt="screen shot 2018-10-12 at 08 53 53" src="https://user-images.githubusercontent.com/4415392/46852783-62552500-cdfc-11e8-86dd-13b90d45f70c.png">

Can I close this?
