### ISSUE TITLE
OpenShift api tagging bug

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/quantum-mechanic#434]
Tagging images using our api implementation should update the existing tags with new image pointers. Currently if the tag already exists it does nothing.

**Comment by andrejonathan** [comment]
@kbristow Hiya can I have a bit more context wrt this bug, thanks

**Comment by kbristow** [comment]
We are trying to mimic the `oc tag` functionality. When you tag an image to a namespace using this, it overwrites the existing tag with the source image stream tag you specify. Our implementation currently only creates new ones. If they already exist, they should be replaced. My guess is we need to pull the entire image stream, see if the tag exists, if it does, remove the existing tag, insert the new one, the do a put to replace the entire image stream definition. Should be similar to the RoleBinding bug fix.
