### ISSUE TITLE
Visual bug on create project in slack-icon squashed

### ISSUE THREAD

**Issue by andrejonathan** [absa-subatomic/quantum-mechanic#476]
![image](https://user-images.githubusercontent.com/36840575/47561275-24d3ba00-d91b-11e8-9b7e-8bb415330c72.png)

**Comment by kbristow** [comment]
Proably just need a better icon.

**Comment by andrejonathan** [comment]
Need to make it so we cant use icons of incorrect size etc...

**Comment by donovanmuller** [comment]
Should we just remove the images completely? They'll never look good in a Thread

**Comment by kbristow** [comment]
I quite like the images... Where do we use them in a thread? Could just avoid the use of them in threads...

**Comment by andrejonathan** [comment]
The images are great just need some control mechanism to ensure they render properly or are resized as needed etc

**Comment by KieranHons** [comment]
Think they were mainly in the bitbucket commands. Can't really remember.. Think it'll mainly be related to the respond messages

**Comment by andrejonathan** [comment]
Image has been fixed
