### ISSUE TITLE
Investigate Prometheus

### ISSUE THREAD

**Issue by chriskieser** [absa-subatomic/quantum-mechanic#506]
Confirm that Prometheus fits our requirements and inspect https://github.com/siimon/prom-client

**Comment by Buzzglo** [comment]
prometheus install via docker, brew, or unpack .tar available for download

brew install prometheus
cd /usr/local/bin

create a prometheus.yml file in this location or 
specify a location using --config.file 
prometheus --config.file="/usr/local/etc/prometheus/prometheus.yml"

localhost:9090 is default per .yml

**Comment by Buzzglo** [comment]
npm install prom-client
