### ISSUE TITLE
QM Usage Metrics

### ISSUE THREAD

**Issue by chriskieser** [absa-subatomic/quantum-mechanic#510]

**Comment by Buzzglo** [comment]
After discussion yesterday we have prioritised the following Metrics at least for the first iteration.
1. Number of active users
2. Commands used and frequency 
3. Number of successful "completed" Commands

I recommend a time start to time to complete, average time taken to complete a command/action/event if time permits.

**Comment by Buzzglo** [comment]
Config file based override, end point specification and help command to be counted.
