### ISSUE TITLE
Add Docker build

### ISSUE THREAD

**Issue by donovanmuller** [absa-subatomic/quantum-mechanic#54]
Add the necessary `Dockerfile` and related resources and documentation around building a Docker image for Quantum Mechanic.

This image should _not_ be required to be run as `root` so as to be compliant with OpenShift's security model (in case deployment to an OpenShift environment is required)

**Comment by kbristow** [comment]
I have made this docker file. However the initial oc login request asks to verify that you want to trust this server because you do not have a cert for it. Do you have suggestions on what I should do about that for a general use case?

**Comment by donovanmuller** [comment]
I believe you can add an option to ignore TLS verification. Given that the certificate is self signed for the OpenShift API it would be difficult to add the Root CA to the image otherwise.

**Comment by kbristow** [comment]
@donovanmuller I know that you can ignore this when calling `oc login` but is that something we want as the default behaviour in our oc client login operation? Or is there a global flag I can set for this docker image?

**Comment by donovanmuller** [comment]
Without loading the Root CA into the base OS, I don't believe so.

**Comment by kbristow** [comment]
Gross. I suppose we can make the default behaviour until we move to the api or your other solution.
