### ISSUE TITLE
Don't fail when certain environments don't exist

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/quantum-mechanic#584]
When performing operations on openshift project environments, don't fail if intermediary environments no longer exist. In our current implementation this means don't fail if DEV or SIT do not exist. Only fail if UAT does not exist since it is 100% a requirement in our pipelines.

**Comment by andrejonathan** [comment]
![image](https://user-images.githubusercontent.com/36840575/49737055-7601f800-fc94-11e8-9732-c8fa581247e3.png)

**Comment by kbristow** [comment]
This is catered for in the overarching PR here: #601
