### ISSUE TITLE
DevOps copying capabilities

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/quantum-mechanic#620]
It would be nice to be able to replicate a devops environment, in multiple ways:

- Automatically create config servers and keycloaks etc when going to prod.
- Automatically copy application build configs and imagestreams etc when migrating clouds.

**Comment by andrejonathan** [comment]
![image](https://user-images.githubusercontent.com/36840575/51890230-3ad29a00-23a4-11e9-9b6b-65074b5db61d.png)

Incorrect message when selecting team for migration, will try fix as part of this task
