### ISSUE TITLE
Display full Jenkins url when build starts

### ISSUE THREAD

**Issue by andrejonathan** [absa-subatomic/quantum-mechanic#645]
Display full Jenkins url when build starts @ *hello* is being built for the first time...

Change in File: src/gluon/commands/jenkins/JenkinsBuild.ts

Refer to : src/gluon/messages/team/DevOpsMessages.ts

Should show:
*hello* is being built for the first time...
Click here to visit Jenkins and see more details
eg https://jenkins-angry-antelope-devops.subatomic.local/job/subatomic-hello/job/hello/job/master/

Can we poll and update when complete or fails?

**Comment by donovanmuller** [comment]
You don't need to poll if the default `Jenkinsfile` contains the [build notification integration](https://docs.atomist.com/user/ci/#jenkins). You can then subscribe on the [build event](https://github.com/atomist/lifecycle-automation/blob/master/lib/handlers/event/build/NotifyPusherOnBuild.ts), correlate with the package that was just built and then push a message.

**Comment by andrejonathan** [comment]
Howdy, I used the word "poll" loosely I guess I should have said "watch for or be notified of " :)

Will investigate the details as per above. Thanks for the feedback

**Comment by andrejonathan** [comment]
I saw software (once) that can do virtual screenshots, so could post screenshots of the build as it goes then additional post link to actually go to the server if want more...just a cool idea I thought.

**Comment by andrejonathan** [comment]
I will just add the link for now and we can investigate a build event subscribtion as per Don above

**Comment by andrejonathan** [comment]
I suggest we add the link for now and we can investigate a build event subscribtion as per Don above?
@kbristow @donovanmuller

**Comment by kbristow** [comment]
Closed by #966
