### ISSUE TITLE
onboard me email error message not user friendly

### ISSUE THREAD

**Issue by andrejonathan** [absa-subatomic/quantum-mechanic#652]

**Comment by andrejonathan** [comment]
![image](https://user-images.githubusercontent.com/36840575/51799429-8e6ca880-2229-11e9-8107-eea1c5c5ed3d.png)
Publishing the regex to the end user seems wrong

Instead: Please ensure you enter a valid email address format

**Comment by kbristow** [comment]
This is a built in atomist response. Don't think we can do anything about that.

**Comment by andrejonathan** [comment]
aha thought it was ours :)
