### ISSUE TITLE
Create application, enter a name

### ISSUE THREAD

**Issue by andrejonathan** [absa-subatomic/quantum-mechanic#657]
![image](https://user-images.githubusercontent.com/36840575/51891136-d2d18300-23a6-11e9-88e7-170e2b0969c6.png)

 Is this superflous as we could just use the Bitbucket application name? Opens us and users up to having an application name different from the BItbucket name.

**Comment by donovanmuller** [comment]
This was primarily for a human readable name. E.g. `My Really Cool App` vs. `really-cool` if `really-cool` was the Bitbucket repo name

**Comment by andrejonathan** [comment]
I would take consistent naming vs human readable naming but just me I guess, thanks for the feedback
