### ISSUE TITLE
Secondary channel invite failure handling bug

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/quantum-mechanic#666]
When a secondary channel is defined in the config but does not exist in slack, the invite user to channel code does not return a string, but a Promise. This doesnt throw an error and instead results in some very strange results. The function here should probably be updated to have better return type information:
https://github.com/absa-subatomic/quantum-mechanic/blob/0c9c83f63d3607fccd9f80a24c18da32db4f8197/src/gluon/services/member/OnboardMemberService.ts#L10

**Comment by andrejonathan** [comment]
The fix will now add the channels to the success array even if they fail, I wish to rework the error handling
