### ISSUE TITLE
Linking slack channel resilience

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/quantum-mechanic#670]
When linking a slack channel, users tend to use the `#slack-channel-name` value occassionally. Perhaps catching such a situation and pulling the correct value we need from the data would be beneficial.

**Comment by andrejonathan** [comment]
![image](https://user-images.githubusercontent.com/36840575/52397054-a3b0c500-2abc-11e9-90dc-3ac50db4873d.png)
This is what happens if the user adds the # in-front of the name

**Comment by andrejonathan** [comment]
if the user mis-types the "existing" channel then a new channel is created based on the typo

**Comment by andrejonathan** [comment]
As slack does some black magic when the user types in the # (see above), I have just added validation to fail if a # is included in the user input. 

It seems like it would be impossible to get the original intended channel name from 
**#_cfrket4fk_jumpy-je**l as the channel name in this example is supposed to be **jumpy-jellyfish**

**Comment by andrejonathan** [comment]
closed and done
