### ISSUE TITLE
Broadcast Event for Announcements in General

### ISSUE THREAD

**Issue by chriskieser** [absa-subatomic/quantum-mechanic#712]
We would like to have event handlers put in place to send out team wide announcements. In particular it would be nice if we could add buttons to these announcements. This would be useful for situations such as: 

We have a new version of the java s2i image. To begin using this image, click the button below.

BUTTON GOES HERE

**Comment by chriskieser** [comment]
Fancy!

**Comment by andrejonathan** [comment]
Actioned and PR'd to master
