### ISSUE TITLE
Using existing Slack channel causes "channel could not be created error"

### ISSUE THREAD

**Issue by chriskieser** [absa-subatomic/quantum-mechanic#786]
![Uploading Screenshot 2019-04-10 at 14.33.08.png…]()

**Comment by chriskieser** [comment]
![Screenshot 2019-04-10 at 14 33 08](https://user-images.githubusercontent.com/3274639/55879468-fed76480-5b9e-11e9-9ef6-08b9cfd326a5.png)

**Comment by andrejonathan** [comment]
@chriskieser I cannot reproduce this bug, can we have more details or please see if you are still getting the error on your side

**Comment by chriskieser** [comment]
Will test and revert

**Comment by chriskieser** [comment]
Working as expected. Closing
