### ISSUE TITLE
Add regex verifier to config for user name

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/quantum-mechanic#796]
Add a customisable verifier regex to assert that users enter their usernames correctly.

**Comment by andrejonathan** [comment]
Should be an ab number?

**Comment by kbristow** [comment]
No, it should be a configurable option

**Comment by andrejonathan** [comment]
Yes configurable but for us its an ab number, yes?

**Comment by kbristow** [comment]
Probably just enforce lower case and a domain... not everyone uses ab numbers.
