### ISSUE TITLE
Buttons should dissapear after migration approval or cancellation

### ISSUE THREAD

**Issue by andrejonathan** [absa-subatomic/quantum-mechanic#816]
![image](https://user-images.githubusercontent.com/36840575/56786647-fd8e7480-67f9-11e9-8ac9-f6f32b375a51.png)

See src/gluon/events/team/TeamOpenShiftCloudMigrated.ts and src/gluon/commands/team/ReRunMigrateTeamCloud.ts for a code example

**Comment by kbristow** [comment]
Closed by #821
