### ISSUE TITLE
ProjectProdCompleteMessage template message

### ISSUE THREAD

**Issue by Buzzglo** [absa-subatomic/quantum-mechanic#857]
Location of file:
src/gluon/messages/prod/ProdRequestMessages::getProjectProdCompleteMessage

Current message:
"*Please Note:* If you have not already done so, your Jenkins OpenShift client plugin needs to be configured with the correct production OpenShift cluster details.
Contact your system admin for help if necessary." - There is currently this at the end of the one message. We need to insert a confluence link there.

Should be overridden to something along these line.
"*Please Note:* If you have not already done so, your Jenkins OpenShift client plugin needs to be configured with the correct production OpenShift cluster details. See the guide on doing this here: link to confluence. Contact your system admin for help if necessary"

**Comment by Buzzglo** [comment]
Additionally change public properties to getters.

**Comment by kbristow** [comment]
@Buzzglo was this not completed?

**Comment by Buzzglo** [comment]
VPN access not working, the commit regarding new line characters to be sorted then this issue can be closed. Should be resolved by tomorrow the 17th May 2019

**Comment by kbristow** [comment]
These issues should be unrelated to the internal requirements btw. But that has been closed so I am closing this issue.
