### ISSUE TITLE
Restructure the current project layout

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/quantum-mechanic#99]
As the project is growing it is getting more difficult to understand where to find particular functionality.
As a start I propose creating sub directories under team, member, project etc folders to seperate events handlers, ingesters and commands. I.E for team:

- team
  - /events
  - /commands
  - /ingesters

GraphQL strings should also be moved to the graphql folder in suitable subdirectories (I.E. subscriptions, queries, etc) and then invoked programmatically.

**Comment by cdupuis** [comment]
Yeah, we've been moving to the following structure:

* src
  * handlers
    * events
    * commands
  * ingesters
  * graphql
    * fragment
    * query
    * subscription
